### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mhadji05** [ActiveNick/Unity-Text-to-Speech#3]
![image](https://user-images.githubusercontent.com/22151801/68529651-5f7f7900-0309-11ea-9cf9-2351612e1dcd.png)

where can i find that fields?

**Comment by ActiveNick** [comment]
There's clear instructions in the README on the front page of this repo. You can get a free trial key here: https://azure.microsoft.com/en-us/try/cognitive-services/?api=speech-services
